"""Land 33 MediaPipe-topology landmarks on the 22-bone rig, as rotations. No bpy, no numpy.

The missing tool in the clean chain. A video model generates a performance; MediaPipe
regresses 33 world landmarks per frame; **this module turns those positions into joint
rotations on the performer's own skeleton.** `tools/lift_solve.py` is the Blender-side
applier; everything decidable without Blender is decided here, so its tests run in
milliseconds and its arithmetic can be checked against mathematics rather than against a
render.

--------------------------------------------------------------------------------
Why this is a rotation solve and not a retarget

Positions do not determine rotations. A limb segment's direction fixes two of a bone's
three rotational degrees of freedom; the third — twist about the segment's own axis —
leaves every landmark on that segment exactly where it was. G16 in
`docs/research-grounding-e08.md` says this in the literature's words: *positions
underdetermine twist*, so a position-only stream needs a separate rotation solve with
pole/twist references rather than an endpoint fit.

So every bone here is solved as **swing + twist**, and the swing is a measurement: the
observed segment direction fixes it outright. The twist is not, and the distinction is
worth stating exactly because it is easy to get backwards.

**A parent's twist is invisible to positions even when it has a child.** Twisting the
upper arm about its own axis moves nothing on the upper arm and does not move the elbow;
the forearm can then be re-aimed at the observed wrist from the new frame, so every twist
angle explains the same landmarks. The twist becomes recoverable only under an added
**constraint**, and this module adds the anatomical one: *the child joint bends about a
fixed hinge axis carried from the bind pose* (`hinge_hint` in MODEL — the character's own
lateral axis, which is where an elbow and a knee actually hinge). The parent's twist is
then whatever carries that hinge axis onto the observed bend plane.

So `underdetermined` means one thing and the report must not blur it: **no bend, no
twist.** Where the child does not bend on a frame there is no bend plane, the constraint
says nothing, and the twist is set to zero and named rather than invented. Where a bone
has no child past its tail at all — a wrist with nothing past the hand, an ankle with
nothing past the toe — it is underdetermined on every frame. G16's sentence, made
mechanical.

--------------------------------------------------------------------------------
What the round trip proves, stated exactly, because it is easy to overclaim

Each bone's rotation is *constructed* to carry its rest direction onto its observed
direction. So `fk_sites(rest, solve_frame(rest, obs))` reproduces `obs` as an algebraic
identity — not as a fit — for every site the model determines, whenever

  (a) the observation was generated by this rig's own kinematics, and
  (b) the motion lies inside this module's parameterisation (see MODEL below).

That is what `tests/test_lift_solve.py` pins at 1e-9 of the character's own bbox diagonal.
It proves the **inversion is exact**. It does not prove the model is adequate, and those
are different claims:

* Where the observation comes from a *different* body — a detector regressing a generic
  adult — segment lengths disagree with the rig's and the reproduction carries a residual.
  That residual is the bone-length measurement (`bone_length_residuals`), not a defect.
* Where the authored motion used degrees of freedom this model does not carry (`spine`,
  `neck` — see MODEL), the solve folds them into their neighbours and the reproduction
  carries a residual there too. That is the **model gap**, and it is measured on the
  authored ground truth with no detector in the loop, so it can be told apart from
  detector noise.

Both residuals are quantities to report. Neither is a threshold this module owns.

--------------------------------------------------------------------------------
MODEL — what is solved, what is held, and why. This IS the mapping table.

The 33-landmark topology does not carry one landmark per rig bone, so three bones are
held at identity with the reason recorded rather than being handed a rotation invented to
fill the gap:

* **`spine` — HELD.** There is no mid-torso landmark between the hips and the shoulders in
  the 33. The whole pelvis→shoulder rotation is carried on `chest`, whose pivot is then
  fixed and whose solve is exact. Splitting it across `spine` and `chest` would need a
  quantity nothing observes.
* **`neck` — HELD.** The 33 give one head frame (nose + two ears), not two. All head
  orientation rides `head`.
* **the five facial markers (`nose`, `eye.*`, `ear.*`) — HELD.** Registered
  non-deforming in `sitelist`: no vertex is weighted to them, so a rotation on one cannot
  change a rendered pixel.

Fingers are unused — the performer has mitten hands — and so are the heels, the mouth
corners and the six eye points. Every unused index is listed in `UNUSED_LANDMARKS` with
its reason, because an omission nobody wrote down reads as an oversight later.
"""

import math

from .errors import ArmatureError, GateFailure
from . import sitelist

TOOL_VERSION = "E09.1"

#: Position round-trip tolerance, as a fraction of the CHARACTER'S OWN bbox diagonal — a
#: global constant in metres must not govern a local feature. 1e-9 sits far above float64
#: noise on a chain this shallow and far below any error a defect would produce.
ROUND_TRIP_TOL_FRAC = 1e-9
#: Rotation round-trip tolerance, radians. Same reasoning, and an angle needs no scale.
ROTATION_TOL_RAD = 1e-9

#: Below this, a cross product of two unit-ish directions is noise rather than a plane, so
#: the twist it would define is underdetermined. Dimensionless: it is compared against the
#: product of the two segment lengths, so it scales with the character.
COLLINEAR_SIN_EPS = 1e-6


class SolveError(ArmatureError):
    """The landmarks do not present what the solve requires."""


class SolveGate(GateFailure):
    """The solver's own round trip did not close. Never a tuning target — a defect."""

    gate = "SOLVE"


# --------------------------------------------------------------- the 33, by index

#: BlazePose / MediaPipe Pose Landmarker topology, index -> name. Held as data so a
#: version bump that reorders them fails loudly in one place instead of quietly
#: everywhere.
POSE_LANDMARKS = (
    "nose",                                                       # 0
    "left_eye_inner", "left_eye", "left_eye_outer",               # 1-3
    "right_eye_inner", "right_eye", "right_eye_outer",            # 4-6
    "left_ear", "right_ear",                                      # 7-8
    "mouth_left", "mouth_right",                                  # 9-10
    "left_shoulder", "right_shoulder",                            # 11-12
    "left_elbow", "right_elbow",                                  # 13-14
    "left_wrist", "right_wrist",                                  # 15-16
    "left_pinky", "right_pinky",                                  # 17-18
    "left_index", "right_index",                                  # 19-20
    "left_thumb", "right_thumb",                                  # 21-22
    "left_hip", "right_hip",                                      # 23-24
    "left_knee", "right_knee",                                    # 25-26
    "left_ankle", "right_ankle",                                  # 27-28
    "left_heel", "right_heel",                                    # 29-30
    "left_foot_index", "right_foot_index",                        # 31-32
)

#: rig landmark name -> MediaPipe index. **The `_L` / `_R` reading is a claim, not a
#: fact:** MediaPipe names a landmark by the *person's* own left and right, and the rig's
#: `_L` is likewise the character's own left, so they should correspond directly. A
#: mirrored reading would produce a solve that round-trips perfectly and is wrong, so the
#: measuring tool checks both assignments against known ground truth and reports which
#: fits — the convention is measured, never assumed.
SITE_FROM_LANDMARK = {
    "nose": 0,
    "ear_L": 7, "ear_R": 8,
    "shoulder_L": 11, "shoulder_R": 12,
    "elbow_L": 13, "elbow_R": 14,
    "wrist_L": 15, "wrist_R": 16,
    "hand_end_L": 19, "hand_end_R": 20,
    "hip_L": 23, "hip_R": 24,
    "knee_L": 25, "knee_R": 26,
    "ankle_L": 27, "ankle_R": 28,
    "toe_L": 31, "toe_R": 32,
}

#: Every index the solve does not read, with the reason. Written down because an omission
#: nobody recorded reads as an oversight to the next session.
UNUSED_LANDMARKS = {
    1: "left_eye_inner — the mesh carries no eye feature; the head frame uses nose + ears",
    2: "left_eye — same", 3: "left_eye_outer — same",
    4: "right_eye_inner — same", 5: "right_eye — same", 6: "right_eye_outer — same",
    9: "mouth_left — the mesh carries no mouth feature",
    10: "mouth_right — same",
    17: "left_pinky — mitten hands; the rig has no finger bones",
    18: "right_pinky — same", 21: "left_thumb — same", 22: "right_thumb — same",
    29: "left_heel — the ankle bone's tail is the toe; the heel would fix the foot's twist "
        "but the rig has no bone past the ankle to carry it",
    30: "right_heel — same",
}

#: The rig sites this module places by forward kinematics but never observes. Recorded so
#: a reader can see at a glance which positions in a solved frame are DERIVED.
UNOBSERVED_SITES = (
    "crotch", "spine_base", "chest_base", "neck_base", "head_base", "head_top",
    "shoulder_line", "eye_L", "eye_R",
    "nose_tip", "eye_L_tip", "eye_R_tip", "ear_L_tip", "ear_R_tip",
)

#: The character's own lateral axis, and the hinge datum for every limb. This rig's
#: measured `left_x_sign` lives on X (E07's manifest), so an elbow and a knee bend about
#: X. It is a *hint*: what is used is its component perpendicular to that bone's own rest
#: direction, so it never has to be exactly the hinge, only unambiguously near it.
LATERAL_AXIS = (1.0, 0.0, 0.0)

#: bone -> how it is solved. `("frame", x_hint_pair, y_hint_pair)` builds an orthonormal
#: frame on both sides and takes the rotation between them; `("direction", tail_site,
#: twist_site_or_None, hinge_hint)` swings the bone's own rest segment onto its observed
#: one and recovers the twist by carrying `hinge_hint` onto the observed bend plane of the
#: next segment; `("hold", reason)` is a bone the 33 cannot determine, named rather than
#: filled.
MODEL = {
    "hips":  ("frame", ("hip_L", "hip_R"), ("shoulder_mid", "hip_mid")),
    "spine": ("hold", "no mid-torso landmark exists in the 33; the whole pelvis-to-"
                      "shoulder rotation rides `chest`, whose pivot is then fixed"),
    "chest": ("frame", ("shoulder_L", "shoulder_R"), ("shoulder_mid", "hip_mid")),
    "neck":  ("hold", "the 33 give one head frame (nose + two ears), not two; all head "
                      "orientation rides `head`"),
    "head":  ("frame", ("ear_L", "ear_R"), ("nose", "ear_mid")),

    "nose":  ("hold", "registered non-deforming in sitelist — no vertex is weighted to it"),
    "eye.L": ("hold", "registered non-deforming"),
    "eye.R": ("hold", "registered non-deforming"),
    "ear.L": ("hold", "registered non-deforming"),
    "ear.R": ("hold", "registered non-deforming"),

    "shoulder.L": ("direction", "elbow_L", "wrist_L", LATERAL_AXIS),
    "elbow.L":    ("direction", "wrist_L", "hand_end_L", LATERAL_AXIS),
    "wrist.L":    ("direction", "hand_end_L", None, LATERAL_AXIS),
    "shoulder.R": ("direction", "elbow_R", "wrist_R", LATERAL_AXIS),
    "elbow.R":    ("direction", "wrist_R", "hand_end_R", LATERAL_AXIS),
    "wrist.R":    ("direction", "hand_end_R", None, LATERAL_AXIS),

    "hip.L":   ("direction", "knee_L", "ankle_L", LATERAL_AXIS),
    "knee.L":  ("direction", "ankle_L", "toe_L", LATERAL_AXIS),
    "ankle.L": ("direction", "toe_L", None, LATERAL_AXIS),
    "hip.R":   ("direction", "knee_R", "ankle_R", LATERAL_AXIS),
    "knee.R":  ("direction", "ankle_R", "toe_R", LATERAL_AXIS),
    "ankle.R": ("direction", "toe_R", None, LATERAL_AXIS),
}


# ------------------------------------------------------------------ small numerics

def _sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def _scale(a, k):
    return (a[0] * k, a[1] * k, a[2] * k)


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def _norm(a):
    return math.sqrt(_dot(a, a))


def _unit(a, what="a direction"):
    n = _norm(a)
    if n < 1e-12:
        raise SolveError(f"{what} has zero length; it cannot be normalised")
    return _scale(a, 1.0 / n)


def _mid(a, b):
    return _scale(_add(a, b), 0.5)


def mat_mul(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(3)) for j in range(3))
                 for i in range(3))


def mat_vec(m, v):
    return tuple(sum(m[i][k] * v[k] for k in range(3)) for i in range(3))


def mat_t(m):
    return tuple(tuple(m[j][i] for j in range(3)) for i in range(3))


IDENTITY = ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))


def axis_angle(axis, theta):
    """Rodrigues rotation about a unit axis."""
    x, y, z = axis
    c, s = math.cos(theta), math.sin(theta)
    t = 1.0 - c
    return ((t * x * x + c,     t * x * y - s * z, t * x * z + s * y),
            (t * x * y + s * z, t * y * y + c,     t * y * z - s * x),
            (t * x * z - s * y, t * y * z + s * x, t * z * z + c))


def rotation_between(a, b):
    """The minimal rotation carrying unit `a` onto unit `b` — swing with no twist.

    The antiparallel case is the one that bites: the axis is undefined there, so any
    perpendicular does, and one is chosen deterministically rather than left to whatever
    the cross product's float noise produced.
    """
    v = _cross(a, b)
    s, c = _norm(v), _dot(a, b)
    if s < 1e-12:
        if c > 0.0:
            return IDENTITY
        perp = _cross(a, (1.0, 0.0, 0.0))
        if _norm(perp) < 1e-9:
            perp = _cross(a, (0.0, 1.0, 0.0))
        return axis_angle(_unit(perp), math.pi)
    return axis_angle(_scale(v, 1.0 / s), math.atan2(s, c))


def geodesic_deg(a, b):
    """Angle of the rotation carrying `a` onto `b`, in degrees.

    The comparison unit for rotations. Euler triples are compared at everyone's peril —
    the same orientation has several representations and the differences between them are
    not errors.
    """
    r = mat_mul(mat_t(a), b)
    tr = r[0][0] + r[1][1] + r[2][2]
    return math.degrees(math.acos(max(-1.0, min(1.0, (tr - 1.0) / 2.0))))


def frame_from(x_hint, y_hint, what="a frame"):
    """A right-handed orthonormal frame as COLUMNS, from two non-parallel hints.

    Built the same way on both the rest and the observed side, which is the whole
    requirement: the rotation between two frames is correct whatever handed convention
    they share, and wrong the moment they stop sharing it.
    """
    ex = _unit(x_hint, f"{what}: the x hint")
    y = _sub(y_hint, _scale(ex, _dot(y_hint, ex)))
    if _norm(y) < 1e-9 * max(_norm(y_hint), 1e-12):
        raise SolveError(f"{what}: the y hint is parallel to the x hint, so the frame is "
                         f"degenerate and any rotation read from it would be noise")
    ey = _unit(y)
    ez = _cross(ex, ey)
    return ((ex[0], ey[0], ez[0]), (ex[1], ey[1], ez[1]), (ex[2], ey[2], ez[2]))


def _bind_reference(u_rest, hint, bone):
    """The bind-pose hinge axis for a bone, perpendicular to its own rest direction.

    A straight limb has no bend plane in the rest pose — this mannequin stands with
    straight arms and legs — so the twist datum cannot be read off the rest bend. It comes
    from the character's own lateral axis instead, projected perpendicular to the bone.

    **Raises when the hint is parallel to the bone**, which would leave the datum
    undefined and the twist reading off float noise. A T-posed rig with arms along X would
    hit this; this rig's arms hang, and a rig that changes must say so here rather than
    quietly producing a number.
    """
    perp = _sub(hint, _scale(u_rest, _dot(hint, u_rest)))
    if _norm(perp) < 1e-6:
        raise SolveError(
            f"bone {bone!r}: the hinge hint {hint} is parallel to its rest direction, so "
            f"the bind twist datum is undefined and any twist solved against it would be "
            f"noise. Declare a different hinge_hint for this bone in MODEL")
    return _unit(perp)


# ------------------------------------------------------- the hierarchy, from sitelist

def _bones():
    """The registered bones, parents first. Read from `sitelist` so the solver cannot
    acquire a bone the registration never registered."""
    return sitelist.BONES


def site_owner_bones():
    """rig landmark -> the bone whose transform places it. Derived from the registration.

    A bone's own head is placed by its parent chain (a rotation about the head leaves the
    head where it was), so head and tail entries agree wherever they overlap.
    """
    owner = {}
    for b in _bones():
        owner.setdefault(b.head, b.name)
        owner.setdefault(b.tail, b.name)
    return owner


def _derived_points(sites):
    """The two midpoints the torso frames are built on, plus the head's ear midpoint."""
    out = dict(sites)
    out["hip_mid"] = _mid(sites["hip_L"], sites["hip_R"])
    out["shoulder_mid"] = _mid(sites["shoulder_L"], sites["shoulder_R"])
    out["ear_mid"] = _mid(sites["ear_L"], sites["ear_R"])
    return out


# --------------------------------------------------------------------- the adapter

def sites_from_landmarks(world_landmarks):
    """The 33 world landmarks, read into rig site names. Positions only, no conversion.

    `world_landmarks` is a sequence of 33 (x, y, z). The axis convention they arrive in is
    the caller's business — `convert_axes` is where that is dealt with, and it is measured
    rather than assumed.
    """
    if len(world_landmarks) != len(POSE_LANDMARKS):
        raise SolveError(
            f"expected {len(POSE_LANDMARKS)} world landmarks, got {len(world_landmarks)}; "
            f"a partial landmark list would solve into a pose with invented joints")
    out = {}
    for site, idx in SITE_FROM_LANDMARK.items():
        p = world_landmarks[idx]
        out[site] = (float(p[0]), float(p[1]), float(p[2]))
    return out


def convert_axes(sites, basis):
    """Rotate landmark positions from the detector's frame into the rig's, by a 3x3.

    Kept as an explicit argument rather than hard-coded: MediaPipe's world landmarks are
    image-aligned, so the correct basis depends on where the camera was, and the whole
    point of measuring it against known ground truth is that a wrong basis produces a
    solve that round-trips perfectly and is wrong.
    """
    return {k: mat_vec(basis, v) for k, v in sites.items()}


def hip_center(sites):
    """Move the hip midpoint to the origin. MediaPipe world landmarks are hip-origin
    already; doing it here as well means a caller cannot forget, and makes the rest-side
    and observed-side conventions the same one."""
    m = _mid(sites["hip_L"], sites["hip_R"])
    return {k: _sub(v, m) for k, v in sites.items()}


# ------------------------------------------------------------------------ the solve

def solve_frame(rest, obs):
    """Joint rotations on the 22-bone rig from one frame of observed site positions.

    `rest` is the rig's own landmark table (E07's manifest). `obs` holds the observed
    positions of the sites in `SITE_FROM_LANDMARK`. Returns a dict carrying

      * `local`  — bone -> 3x3 local rotation, in the same world-axis convention
                   `armature_core.walk.rotation_matrix` produces, so the applier, the
                   authored ground truth and this solve all speak one language;
      * `total`  — bone -> 3x3 accumulated rotation (parent-composed);
      * `root`   — the hips' translation, and what it does and does not mean;
      * `underdetermined` — bone -> why its twist was not recovered;
      * `held`   — bone -> why it carries no rotation at all.

    Nothing here is a gate. `round_trip_report` is where a defect raises.
    """
    missing = [s for s in SITE_FROM_LANDMARK if s not in obs]
    if missing:
        raise SolveError(f"observed sites missing: {sorted(missing)}; the solve would place "
                         f"those joints at invented positions with nothing pointing at it")
    rest_missing = [s for s in SITE_FROM_LANDMARK if s not in rest]
    if rest_missing:
        raise SolveError(f"the rest landmark table is missing {sorted(rest_missing)}")

    r = _derived_points(rest)
    o = _derived_points(obs)

    local, total = {}, {}
    underdetermined, held, conditioning = {}, {}, {}

    for bone in _bones():
        name = bone.name
        rule = MODEL.get(name)
        if rule is None:
            raise SolveError(f"bone {name!r} is registered in sitelist but MODEL says "
                             f"nothing about it; a bone with no recorded rule would be "
                             f"silently held at identity")
        parent_total = total[bone.parent] if bone.parent else IDENTITY

        if rule[0] == "hold":
            local[name] = IDENTITY
            held[name] = rule[1]

        elif rule[0] == "frame":
            (xa, xb), (ya, yb) = rule[1], rule[2]
            f_rest = frame_from(_sub(r[xa], r[xb]), _sub(r[ya], r[yb]), f"{name} rest frame")
            f_obs = frame_from(_sub(o[xa], o[xb]), _sub(o[ya], o[yb]), f"{name} observed frame")
            world = mat_mul(f_obs, mat_t(f_rest))
            local[name] = mat_mul(mat_t(parent_total), world)

        elif rule[0] == "direction":
            tail_site, twist_site, hinge_hint = rule[1], rule[2], rule[3]
            head_site = bone.head
            u_rest = _unit(_sub(r[tail_site], r[head_site]), f"{name} rest segment")
            seg_obs = _sub(o[tail_site], o[head_site])
            u_obs = _unit(seg_obs, f"{name} observed segment")
            v = mat_vec(mat_t(parent_total), u_obs)
            swing = rotation_between(u_rest, v)

            twist_ok = False
            if twist_site is not None:
                nxt = _sub(o[twist_site], o[tail_site])
                # `u_obs` is already a unit vector, so |cross| / |nxt| IS the sine of the
                # observed bend angle. **Measured 2026-08-11:** the first version divided
                # by |seg_obs| * |nxt| as well, which made the "sine" scale with the bone's
                # own length and return values above 1 — a conditioning number outside its
                # own range, and a collinearity threshold that meant something different
                # for a thigh than for a forearm.
                n_obs = _cross(u_obs, nxt)
                len_next = _norm(nxt)
                # How well-conditioned this twist is, reported per bone per frame. A hard
                # threshold alone would be a lie by omission: a limb bent half a degree
                # clears it and its twist is still nearly noise.
                conditioning[name] = (_norm(n_obs) / len_next) if len_next > 0 else 0.0
                if _norm(n_obs) > COLLINEAR_SIN_EPS * len_next:
                    n_ref = _bind_reference(u_rest, hinge_hint, name)
                    n_tgt = mat_vec(mat_t(parent_total), _unit(n_obs))
                    n_tgt = _sub(n_tgt, _scale(v, _dot(n_tgt, v)))
                    n_sw = mat_vec(swing, n_ref)
                    n_sw = _sub(n_sw, _scale(v, _dot(n_sw, v)))
                    if _norm(n_tgt) > 1e-12 and _norm(n_sw) > 1e-12:
                        n_tgt, n_sw = _unit(n_tgt), _unit(n_sw)
                        theta = math.atan2(_dot(_cross(n_sw, n_tgt), v), _dot(n_sw, n_tgt))
                        # **A hinge is a LINE, not a ray**, and this is the second defect
                        # the tests caught. An elbow that bends the other way flips the
                        # observed bend normal, and matching the datum to that ray forced a
                        # 180-degree twist onto the PARENT — 178.9 degrees of error on a
                        # bone whose authored motion was a clean swing. What the constraint
                        # actually says is that the hinge axis lies IN the bend plane's
                        # normal direction, either way round, so theta is determined only
                        # modulo pi. The representative taken is the smallest one: a hinge
                        # joint's twist relative to its parent is near zero, and choosing
                        # the minimal-twist branch is that assumption made explicit rather
                        # than left to which way the limb happened to bend.
                        if theta > math.pi / 2.0:
                            theta -= math.pi
                        elif theta <= -math.pi / 2.0:
                            theta += math.pi
                        local[name] = mat_mul(axis_angle(v, theta), swing)
                        twist_ok = True
            if not twist_ok:
                local[name] = swing
                underdetermined[name] = (
                    "no child landmark past this bone's tail — nothing observed can carry "
                    "the hinge constraint that would fix the twist"
                    if twist_site is None else
                    f"the segment to {twist_site} is collinear with this bone on this "
                    f"frame, so there is no bend plane for the hinge datum to land on")
        else:
            raise SolveError(f"bone {name!r} has unknown rule {rule[0]!r}")

        total[name] = mat_mul(parent_total, local[name])

    # The hips' TRANSLATION CHANNEL, not its total offset — the quantity
    # `author_walk.apply_pose` keys and the quantity `fk_sites` adds on top of the pivot
    # term. **Measured 2026-08-11, the first defect this module's own gate caught:** the
    # first version returned the total, `fk_sites` then added the pivot term a second
    # time, and the whole body landed 0.0036 out under any hips rotation while a
    # hips-identity motion round-tripped perfectly. A bug that hides whenever the root
    # does not rotate is exactly the kind this gate exists for.
    want_total = _sub(o["hip_mid"], mat_vec(total["hips"], r["hip_mid"]))
    pivot_term = _sub(rest["crotch"], mat_vec(local["hips"], rest["crotch"]))
    root = _sub(want_total, pivot_term)
    return {
        "local": local,
        "total": total,
        "root": {
            "hips_delta_translation": root,
            "means": ("the translation that puts the rest hip midpoint on the observed "
                      "one. It is NOT metric root motion: MediaPipe world landmarks are "
                      "hip-origin and the model card puts metric depth out of scope, so "
                      "locomotion through the scene is not recoverable from this stream"),
        },
        "underdetermined": underdetermined,
        "twist_conditioning": conditioning,
        "held": held,
        "tool_version": TOOL_VERSION,
    }


def fk_sites(rest, solved):
    """Every rig landmark's position under a solved frame. The inverse direction.

    Composed exactly as `armature_core.walk.forward_kinematics` composes it — a bone's
    delta is its parent's composed with a rotation about the bone's own REST head — so a
    solve can be checked against the authored ground truth without two kinematics
    implementations quietly disagreeing.
    """
    local, root = solved["local"], solved["root"]["hips_delta_translation"]
    deltas = {}
    for bone in _bones():
        name = bone.name
        rot = local[name]
        p0 = rest[bone.head]
        t_local = _sub(p0, mat_vec(rot, p0))
        if bone.parent is None:
            deltas[name] = (rot, _add(t_local, root))
        else:
            rp, tp = deltas[bone.parent]
            deltas[name] = (mat_mul(rp, rot), _add(mat_vec(rp, t_local), tp))

    owner = site_owner_bones()
    out = {}
    for site, bone_name in owner.items():
        if site not in rest:
            continue
        rot, t = deltas[bone_name]
        out[site] = _add(mat_vec(rot, rest[site]), t)
    return out


# ---------------------------------------------------------------------- the checks

def round_trip_report(rest, obs, solved, diagonal, tol_frac=ROUND_TRIP_TOL_FRAC,
                      raise_on_fail=True):
    """Does the solve reproduce the positions it was solved from? · ANDON

    **This raises**, inside the module that did the solve, rather than returning a verdict
    for a shell chain to walk past. It is the one check that is a gate here: a solver that
    does not invert its own model is broken, and everything downstream would be quoted
    against a wrong pose while every other number looked reasonable.

    The tolerance is a fraction of the character's own bbox diagonal. `raise_on_fail` is
    NOT a skip flag — it exists so the *measurement* path can report a residual against a
    real detector, where the observation comes from another body and a residual is the
    thing being measured rather than a defect. The gate is armed on the synthetic path,
    which is the one whose invariant is exactness.
    """
    got = fk_sites(rest, solved)
    tol = tol_frac * diagonal
    per_site, worst = {}, {"site": None, "d": 0.0}
    for site in sorted(SITE_FROM_LANDMARK):
        if site not in got:
            continue
        d = _norm(_sub(got[site], obs[site]))
        per_site[site] = d
        if d > worst["d"]:
            worst = {"site": site, "d": d}
    ev = {"gate": "SOLVE", "tolerance": tol, "tolerance_frac_of_diagonal": tol_frac,
          "bbox_diagonal": diagonal, "worst": worst, "per_site": per_site,
          "n_sites": len(per_site),
          "note": ("distance between each observed site and where the solved rotations "
                   "put it; exact by construction when the observation came from this "
                   "rig's own kinematics inside this model")}
    if raise_on_fail and worst["d"] > tol:
        raise SolveGate(
            f"the solve does not reproduce the positions it was solved from: "
            f"{worst['d']:.12f} at site {worst['site']!r} against a tolerance of "
            f"{tol:.12f}. This is an inversion defect, never a number to tune toward", ev)
    ev["verdict"] = f"max {worst['d']:.3e} over {len(per_site)} sites (tolerance {tol:.3e})"
    return ev


def bone_length_residuals(rest, obs):
    """Per bone: how much longer or shorter the observed segment is than the rig's own.

    The measurement that says whether a lift is landing a *different body* on this
    skeleton. Reported per structure and as a fraction of that bone's own rest length —
    never as a length in metres, and never as one number for the whole figure.
    """
    out = {}
    for bone in _bones():
        rule = MODEL.get(bone.name)
        if not rule or rule[0] != "direction":
            continue
        tail = rule[1]
        head = bone.head
        if head not in obs or tail not in obs:
            continue
        rest_len = _norm(_sub(rest[tail], rest[head]))
        obs_len = _norm(_sub(obs[tail], obs[head]))
        if rest_len <= 0:
            raise SolveError(f"bone {bone.name!r} has zero rest length")
        out[bone.name] = {
            "rest_length": rest_len, "observed_length": obs_len,
            "residual_fraction": (obs_len - rest_len) / rest_len,
        }
    return out


def validate_motion_record(frames):
    """The solved frames are a contiguous run and every bone is present. · ANDON

    Lives here rather than in the Blender applier so it can be exercised without a render
    — the same split every other gate in this repo keeps. Both clauses guard failures that
    are silent downstream: a **gap** in the frame numbering gets filled by whatever pose
    the previous keyframe held, and a **missing bone** simply keeps its last rotation.
    Either produces a clip that plays, exports, and passes every count-based check, and
    the stutter reads as the lift being noisy rather than as a frame that never arrived.
    """
    if not frames:
        raise SolveGate("the motion record carries no frames", {"n": 0})
    for i, fr in enumerate(frames):
        if fr.get("frame") != i:
            raise SolveGate(
                f"the solved frames are not a contiguous run from 0: entry {i} says frame "
                f"{fr.get('frame')!r}. A gap filled by the neighbouring pose would play as "
                f"a stutter and be read as detector noise",
                {"index": i, "says": fr.get("frame"), "n": len(frames)})
        local = fr.get("local") or {}
        missing = [b for b in sitelist.ALL_NAMES if b not in local]
        if missing:
            raise SolveGate(
                f"frame {i} carries no rotation for {missing}; a bone left out here would "
                f"hold its previous pose while every gate downstream stayed green",
                {"frame": i, "missing": missing})
    return {"gate": "SOLVE", "n_frames": len(frames),
            "verdict": f"{len(frames)} contiguous frames, all {len(sitelist.ALL_NAMES)} "
                       f"registered bones present on each"}


def compare_rotations(solved_local, authored_local):
    """Per-bone geodesic angle between a solved rotation and an authored one, in degrees.

    Compared as matrices. Two Euler triples that differ can name the same orientation, and
    a report that subtracted them would print an error that is not one.
    """
    out = {}
    for name, want in authored_local.items():
        got = solved_local.get(name)
        if got is None:
            continue
        out[name] = geodesic_deg(want, got)
    return out
